### Get All Action Logs
GET http://localhost:8080/rede-segura/action-logs
Accept: application/json

###

### Get Action Log by ID
GET http://localhost:8080/rede-segura/action-logs/3
Accept: application/json

###

### Create Action Log
POST http://localhost:8080/rede-segura/action-logs
Content-Type: application/json

{
  "vulnerabilityId": 1,
  "action": "Test action",
  "performedById": 1
}

###

### Update Action Log
PUT http://localhost:8080/rede-segura/action-logs/5
Content-Type: application/json

{
  "vulnerabilityId": 1,
  "action": "Updated action",
  "performedById": 1
}

###

### Delete Action Log
DELETE http://localhost:8080/rede-segura/action-logs/4
