### Get All Notifications
GET http://localhost:8080/rede-segura/notifications
Accept: application/json

###

### Get Notification by ID
GET http://localhost:8080/rede-segura/notifications/1
Accept: application/json

###

### Create Notification
POST http://localhost:8080/rede-segura/notifications
Content-Type: application/json

{
  "recipientId": 1,
  "message": "Notification Message",
  "read": false
}

###

### Update Notification
PUT http://localhost:8080/rede-segura/notifications/3
Content-Type: application/json

{
  "recipientId": 1,
  "message": "Updated Notification Message",
  "read": true
}

###

### Delete Notification
DELETE http://localhost:8080/rede-segura/notifications/5
