### Get All Reports
GET http://localhost:8080/rede-segura/reports
Accept: application/json

###

### Get Report by ID
GET http://localhost:8080/rede-segura/reports/1
Accept: application/json

###

### Create Report
POST http://localhost:8080/rede-segura/reports
Content-Type: application/json

{
  "generatedById": 1,
  "content": "Report Content"
}

###

### Update Report
PUT http://localhost:8080/rede-segura/reports/3
Content-Type: application/json

{
  "generatedById": 1,
  "content": "Updated Report Content"
}

###

### Delete Report
DELETE http://localhost:8080/rede-segura/reports/5
