### Get All Servers
GET http://localhost:8080/rede-segura/api/servers
Accept: application/json

###

### Get Server by ID
GET http://localhost:8080/rede-segura/api/servers/3
Accept: application/json

###

### Create Server
POST http://localhost:8080/rede-segura/api/servers
Content-Type: application/json

{
  "name": "Server 1",
  "description": "Server Description",
  "institutionId": 1,
  "responsibleId": 1
}

###

### Update Server
PUT http://localhost:8080/rede-segura/api/servers/3
Content-Type: application/json

{
  "name": "Updated Server",
  "description": "Updated Description",
  "institutionId": 1,
  "responsibleId": 1
}

###

### Delete Server
DELETE http://localhost:8080/rede-segura/api/servers/5
