### Get All Tools
GET http://localhost:8080/rede-segura/tools
Accept: application/json

###

### Get Tool by ID
GET http://localhost:8080/rede-segura/tools/3
Accept: application/json

###

### Create Tool
POST http://localhost:8080/rede-segura/tools
Content-Type: application/json

{
  "name": "Tool 1",
  "description": "Tool Description",
  "integrationDetails": "Integration Details"
}

###

### Update Tool
PUT http://localhost:8080/rede-segura/tools/3
Content-Type: application/json

{
  "name": "Updated Tool",
  "description": "Updated Description",
  "integrationDetails": "Updated Integration Details"
}

###

### Delete Tool
DELETE http://localhost:8080/rede-segura/tools/4
