version: '3.1'

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rede-segura-db
    volumes:
      - mysql-data:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mysql-data: