version: '3.8'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rede-segura-db
    volumes:
      - mysql-data:/data/db
    networks:
      - backend

  dns_recursion:
    image: sameersbn/bind:latest
    networks:
      vulnerable_net:
        ipv4_address: 200.130.38.131
    ports:
      - "9053:53/tcp"
      - "9053:53/udp"
    environment:
      - BIND_USER=root
    command: ["-g", "-c", "/etc/bind/named.conf"]

  ntp_ddos_amplification:
    image: cturra/ntp
    networks:
      vulnerable_net:
        ipv4_address: 200.130.38.132
    ports:
      - "8033:123/udp"

  netbios_exposure:
    image: dperson/samba
    networks:
      vulnerable_net:
        ipv4_address: 200.130.38.133
    ports:
      - "9045:445"
      - "9139:139"
    command: ["-n", "STORAGE"]

  snmp_public_community:
    image: crazymax/snmpd
    networks:
      vulnerable_net:
        ipv4_address: 200.130.38.134
    ports:
      - "8051:161/udp"
    environment:
      - SNMP_COM=public

  samba_outdated_version:
    image: dperson/samba
    networks:
      vulnerable_net:
        ipv4_address: 200.130.38.135
    ports:
      - "9145:445"
      - "9239:139"
    command: ["-n", "STORAGE"]

  exposed_mysql:
    image: mysql:5.7
    networks:
      vulnerable_net:
        ipv4_address: 200.130.38.136
    ports:
      - "8066:3307"
    environment:
      MYSQL_ROOT_PASSWORD: my_secure_password
      MYSQL_DATABASE: test


networks:
  stable_net:
    ipam:
      driver: default
      config:
        - subnet: 200.130.38.128/28
  vulnerable_net:
    ipam:
      driver: default
      config:
        - subnet: 200.130.38.128/28
  backend:
    driver: bridge


volumes:
  mysql-data: