version: '3.8'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rede-segura-db
    volumes:
      - mysql-data:/data/db
    networks:
      backend:
        ipv4_address: 172.30.1.2

  redis-vulnerable:
    build: ./dockerfiles/vulnerable
    container_name: redis-vulnerable
    ports:
      - "6381:6379"
    networks:
      backend:
        ipv4_address: 172.30.1.3

  redis-secure:
    build: ./dockerfiles/secure
    container_name: redis-secure
    ports:
      - "6382:6378"
    networks:
      backend:
        ipv4_address: 172.30.1.4

  tester:
    build: ./dockerfiles/tester
    container_name: tester
    networks:
      backend:
        ipv4_address: 172.30.1.5

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16

volumes:
  mysql-data:
