package br.rnp.redesegura.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ReportDto {

    @NotNull(message = "Generated by ID is required")
    private Long generatedById;

    @NotBlank(message = "Content is required")
    private String content;

}